### ISSUE TITLE
建議：應刪除歷史提交

### ISSUE THREAD

**Issue by Myster7494** [SpeedReach/Soha#1]
建議應刪除歷史提交，否則能從歷史提交中找到FIB位置被刪除前的程式碼
--------------------
祝新年快樂

**Comment by brian030128** [comment]
我印象中 initial commit 就是FIB已經刪除的程式碼了，還是有哪一版上面有答案?

**Comment by Myster7494** [comment]
commit cce9cf4 之前的版本都有
從其和上一個commit 8c476ab 的比較很容易就能看到

**Comment by brian030128** [comment]
欸真的 我以為commit前就清掉了 看來是記錯了
下次如果有類似的活動，我們會特別留意這情況 感謝
